apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  googleCloudBuild:
    projectId: ticketing-dev-494806
  artifacts:
    - image: asia.gcr.io/ticketing-dev-494806/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: asia.gcr.io/ticketing-dev-494806/ticket
      context: ticket
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: asia.gcr.io/ticketing-dev-494806/order
      context: order
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: asia.gcr.io/ticketing-dev-494806/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
          - src: '**/*.css'
            dest: .
